apiVersion: apps/v1
kind: Deployment
metadata:
  name: ganache
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "nt114-fl.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ganache
  template:
    metadata:
      labels:
        app: ganache
    spec:
      containers:
        - name: ganache
          image: {{ .Values.ganache.image }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          args:
            - --dev
            - --http
            - --http.addr
            - 0.0.0.0
            - --http.port
            - "7545"
            - --http.api
            - eth,net,web3,debug,miner,txpool
            - --http.corsdomain
            - "*"
            - --http.vhosts
            - "*"
            - --dev.period
            - "1"
          ports:
            - containerPort: 7545
---
apiVersion: v1
kind: Service
metadata:
  name: ganache
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "nt114-fl.labels" . | nindent 4 }}
spec:
  selector:
    app: ganache
  ports:
    - name: rpc
      port: 7545
      targetPort: 7545