apiVersion: apps/v1
kind: Deployment
metadata:
  name: ganache
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "nt114-fl.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ganache
  template:
    metadata:
      labels:
        app: ganache
    spec:
      containers:
        - name: ganache
          image: {{ .Values.ganache.image }}
          imagePullPolicy: {{ .Values.images.pullPolicy }}
          command:
            - anvil
          args:
            - --host
            - 0.0.0.0
            - --port
            - "7545"
            - --chain-id
            - {{ .Values.ganache.chainId | quote }}
            - --mnemonic
            - {{ .Values.ganache.mnemonic | quote }}
            - --block-time
            - "1"
          ports:
            - containerPort: 7545
---
apiVersion: v1
kind: Service
metadata:
  name: ganache
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "nt114-fl.labels" . | nindent 4 }}
spec:
  selector:
    app: ganache
  ports:
    - name: rpc
      port: 7545
      targetPort: 7545